"""comment table

Revision ID: 00566fe51232
Revises: 
Create Date: 2020-08-03 14:25:57.049420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00566fe51232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=800), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_firstname'), 'comment', ['firstname'], unique=True)
    op.create_index(op.f('ix_comment_lastname'), 'comment', ['lastname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_lastname'), table_name='comment')
    op.drop_index(op.f('ix_comment_firstname'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
